package com.example.Diamondbacks;

public enum MeasureType {
    GEOMETRIC_COMPACTNESS, POPULATION_FATNESS, GRAPH_COMPACTNESS, EQUAL_POPULATION, GEOMETRIC_DEVIATION, POPULATION_DEVIATION, SPLIT_COUNTY_MEASURE, POLITICAL_FAIRNESS , DEVIATION_FROM_AVERAGE
}
