package com.example.Diamondbacks;

public enum MeasureType {
    TOT_POP_EQU, VOT_POP_EQU, CITZEN_POP_EQU,
    GEOMETRIC_COMPACTNESS, GRAPH_COMPACTNESS, POPULATION_FATNESS,
    DEV_AVERAGE_GEO, DEV_AVERAGE_POP,
    DEV_ENACTED_GEO, DEV_ENACTED_POP,
    SPLIT_COUNTY_MEASURE, POLITICAL_FAIRNESS
}
